version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
    ignore:
      - dependency-name: org.apache.maven:maven-plugin-api
      - dependency-name: org.apache.maven:maven-settings
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
