name: CI

on: push

env:
  MAVEN_ARGS: --batch-mode --color=always --no-transfer-progress

jobs:

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ibiqlik/action-yamllint@v3
        with:
          format: colored
          strict: true

  markdown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: avto-dev/markdown-lint@v1
        with:
          args: /github/workspace

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11
          cache: maven
          server-id: sonatype-nexus
          server-username: SERVER_USERNAME
          server-password: SERVER_PASSWORD
      - run: mvn $MAVEN_ARGS dependency:go-offline
      - run: mvn $MAVEN_ARGS verify site
        if: ${{ github.ref != 'refs/heads/main' }}
      - run: mvn $MAVEN_ARGS deploy site-deploy
        if: ${{ github.ref == 'refs/heads/main' }}
        env:
          SERVER_USERNAME: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SERVER_PASSWORD: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
