name: CI build and Deploy

on:
  push:
    # run on all tags
    tags:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build with Maven
        run: mvn clean install